var institutions = [
	new Institution('acad','Academia Belgica'),
	new Institution('acv','ACV'),
	new Institution('assoc','Associatie KU Leuven'),
	new Institution('bb','Boerenbond & Landelijke Gilden'),
	new Institution('bpb','Belgisch Parlement'),
	new Institution('cag','Centrum voor Agrarische Geschiedenis'),
	new Institution('ckrc','Centrum voor Religieuze Kunst en Cultuur'),
	new Institution('ecb','ECB'),
	new Institution('faro','FARO'),
	new Institution('ffin','FOD Financiën'),
	new Institution('fpo','FOD P&O'),
	new Institution('hub','H.U.Brussel'),
	new Institution('kadoc','KADOC'),
	new Institution('kahosl','KaHo SL'),
	new Institution('katho','KATHO'),
	new Institution('kbc','KBC'),
	new Institution('kbin','Koninklijk Belgisch Instituut voor Natuurwetenschappen '),
	new Institution('khbo','Katholieke Hogeschool Brugge-Oostende'),
	new Institution('tmk','Thomas More Kempen'),
	new Institution('khl','KH Leuven'),
	new Institution('khlim','KH Limburg'),
	new Institution('kmkg','Koninklijke Musea voor Kunst en Geschiedenis'),
	new Institution('kmma','Koninklijk Museum van Midden-Afrika'),
	new Institution('kul','KU Leuven'),
	new Institution('lbsn','LIBISnet'),
	new Institution('tma','Thomas More Antwerpen'),
	new Institution('tmm','Thomas More Mechelen'),
	new Institution('libar','Liberaal Archief'),
	new Institution('luca','St-Lukas Brussel/Gent + Lemmensinstituut + Narafi Brussel'),
	new Institution('nbb','Nationale Bank België'),
	new Institution('serv','SERV'),
	new Institution('vdic','VDIC'),
	new Institution('vlp','Vlaams parlement')
];

var subprojects = [
	new SubProject('adlib','Adlib','#heron @pro'),
	new SubProject('alma','Alma'),
	new SubProject('anjou','Bijbel van Anjou','#heron @pro'),
	new SubProject('BKCIRC','BKCIRK - Agora','#limo @pro'),
	new SubProject('blog','Blog',' #libis @pr'),
	new SubProject('br','Bibliotheekraad','#kul @meet'),
	new SubProject('cab','Commissie Algemeen Beheer','#kul @meet'),
	new SubProject('cover','Coverserver voor Bibnet'),
	new SubProject('digit','Vergaderingen ivm digitalisatie: werkgroep digitalisering, …','#kul @meet'),
	new SubProject('etd','Ingest van e-thesissen'),
	new SubProject('exc','Ex Cathedra voor de UB'),
	new SubProject('flan','Flandrica'),
	new SubProject('ict','ICT: vergaderingen voorbereidingen, nota\'s… voor KU leuven'),
	new SubProject('lias','Lias'),
	new SubProject('limo','Limo'),
	new SubProject('lmt','LMT: vergaderingen voorbereidingen, nota\'s...','#libis @meet'),
	new SubProject('locator','Locator','#lbsn @pro'),
	new SubProject('ml','Uitbating MetaLib','#eres @uit'),
	new SubProject('mtub','MTUB: vergaderingen voorbereidingen, nota\'s...','#kul @meet'),
	new SubProject('netman','netman, installatie van CD\'s e.d.','#eres @pro'),
	new SubProject('openid','Openid voor Bibnet','#vlacc @pro'),
	new SubProject('rfid','RFid voor LIBISnet en PBS, organisatie opgeven als noot','#lbsn @pro'),
	new SubProject('scope','Uitbating Scope','#lias @uit'),
	new SubProject('sfx','Uitbating SFX','#eres @uit'),
	new SubProject('stcv','Eenmalige conversie STCV','#lbsn @stev'),
	new SubProject('stuiter','Project: vernieuwing stuiterproxy'),
	new SubProject('team','Teamoverleg: vergaderingen voorbereidingen, nota\'s...','#libis @meet'),
	new SubProject('test','Testen'),
	new SubProject('toegang','Toegangscontrole'),
	new SubProject('training','Training en opleiding'),
	new SubProject('unicat','Unicat','#lbns @pro'),
	new SubProject('verde','Uitbating Verde','#eres @uit'),
	new SubProject('vvbad','Vergaderingen VVBAD','#libis @meet'),
	new SubProject('zizo','Conversies PBS','#pbs @conv'),
	new SubProject('Heron','Heron'),
	new SubProject('info','Informatie aan Zee','#libis @event'),
	new SubProject('lbsndag','LIBISnet gebruikersdag','#libis @event'),
	new SubProject('lzine','LIBISzine','#libis @pr'),
	new SubProject('support','Managementondersteuning Jo','#libis @admin'),
	new SubProject('tool','Tool voor het vervangen van publicaties','#lirias @pro'),
	new SubProject('ontw','Ontwikkelingen @mire','#lirias'),
	new SubProject('ng','Next Generation Lirias','#lirias'),
	new SubProject('V4','Versie 4 Limo','#limo @pro'),
	new SubProject('link','Link Builder','#limo')
];
